apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: whoami-cert-staging
  namespace: whoami
spec:
  commonName: whoami.1.${CLUSTERNAME}.${DOMAINNAME}
  secretName: whoami-cert-staging
  dnsNames:
    - whoami.1.${CLUSTERNAME}.${DOMAINNAME}
  issuerRef:
    kind: ClusterIssuer
    name: myissuer
