---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: whoami-ingress
  namespace: whoami
  annotations:
    kubernetes.io/ingress.class: "traefik-1"
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`whoami-1.1.${CLUSTERNAME}.${DOMAINNAME}`)
      services:
        - name: whoami
          port: 80
  tls:
    secretName: whoami-1-cert-staging
