apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: myissuer
  namespace: cert-manager
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: david.blaskow@traefik.io
    privateKeySecretRef:
      name: my-account-key
    solvers:
    - http01:
        ingress:
          ingressClassName: traefik-1
          ingressTemplate:
            metadata:
              annotations:
                "traefik.ingress.kubernetes.io/router.priority": "1000"
